name: launch_at_startup
description: This plugin allows Flutter desktop apps to Auto launch on startup / login.
version: 0.5.1
homepage: https://leanflutter.dev/documentation/launch_at_startup
repository: https://github.com/leanflutter/launch_at_startup
issue_tracker: https://github.com/leanflutter/launch_at_startup/issues
documentation: https://leanflutter.dev/documentation/launch_at_startup

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  win32_registry: ^2.0.0

dev_dependencies:
  dependency_validator: ^3.0.0
  # flutter_test:
  #   sdk: flutter
  mostly_reasonable_lints: ^0.1.2
