name: launch_at_startup_example
description: Demonstrates how to use the launch_at_startup plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  launch_at_startup:
    path: ../
  package_info_plus: ^8.0.0
  preference_list: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2
  msix: ^3.16.7

flutter:
  uses-material-design: true

msix_config:
  display_name: launch_at_startup_example
  publisher_display_name: LeanFlutter
  identity_name: dev.leanflutter.examples.launchatstartupexample
  msix_version: 1.0.0.0

