name: Release Flatpak

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: windows-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4.1.5

      - name: Extract Version from pubspec.yaml
        id: extract_version
        run: |
          $VERSION = Select-String  -Path ".\pubspec.yaml" -Pattern "^\s*version:\s*(\d+\.\d+\.\d+)" -CaseSensitive | ForEach-Object{ $_.Matches.Groups[1].Value }
          echo version=$VERSION >> $env:GITHUB_OUTPUT

  Build-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: version
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0


      - name: Get commit of tag
        id: get_commit
        run: |
          TAG_NAME="v${{ needs.version.outputs.version }}"
          COMMIT_HASH=$(git rev-list -n 1 "$TAG_NAME")
          echo "Commit for $TAG_NAME is $COMMIT_HASH"
          echo "commit_hash=$COMMIT_HASH" >> "$GITHUB_OUTPUT"

      - name: Clone flatpak-flutter
        run: |
          git clone https://github.com/TheAppgineer/flatpak-flutter.git
          mkdir flatpak-flutter/brisk

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Update flatpak-flutter.yml
        run: |
          pip install pyyaml
          ./linux/packaging/flatpak/update-flatpak-flutter.py linux/packaging/flatpak/flatpak-flutter.yml --tag v${{ needs.version.outputs.version }} --commit ${{ steps.get_commit.outputs.commit_hash }}
          cat linux/packaging/flatpak/flatpak-flutter.yml

      - name: Install dependencies
        run: pip install aiohttp pyyaml toml

      - name: Install flatpak
        run: |
          sudo apt update
          sudo apt install -y flatpak
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak remote-ls flathub > /dev/null
          flatpak install -y --user flathub org.flatpak.Builder

      - name: Run flatpak-flutter
        run: |
          cp linux/packaging/flatpak/flatpak-flutter.yml flatpak-flutter/brisk/
          cd flatpak-flutter/brisk/
          ../flatpak-flutter.py flatpak-flutter.yml
          ls -la

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push update to flathub release branch
        env:
          PAGES_REPO_PAT: ${{ secrets.REPO_PAT }}
        run: |
          # --- Debugging: Initial state ---
          echo "Current directory before cloning: $(pwd)"

          # Clone the flathub-test repository
          git clone https://x-access-token:${PAGES_REPO_PAT}@github.com/AminBhst/flathub-test.git
          cd flathub-test

          echo "Current directory after cloning and entering flathub-test: $(pwd)"
          echo "Content of flathub-test before cleanup:"
          ls -la

          # --- Step 1: Create and checkout the release branch ---
          git checkout -B release-${{ needs.version.outputs.version }}

          # --- Step 2: Delete everything except .git and shared-modules ---
          # Use find to list items that are NOT .git and NOT shared-modules
          # This helps in debugging what will be deleted
          echo "Items to be deleted (excluding .git and shared-modules):"
          find . -maxdepth 1 -mindepth 1 -not -name ".git" -not -name "shared-modules"

          # Perform the deletion
          # We use xargs for safer handling of file names with spaces/special chars
          find . -maxdepth 1 -mindepth 1 -not -name ".git" -not -name "shared-modules" -print0 | xargs -0 rm -rf

          echo "Content of flathub-test after cleanup:"
          ls -la

          # --- Debugging: Source directory content ---
          echo "Content of source directory (../flatpak-flutter/brisk/):"
          ls -la ../flatpak-flutter/brisk/

          # --- Step 3: Copy everything from source into the current directory ---
          # Use 'cp -r' to copy directories recursively and '.' to copy into the current directory
          # The '*' ensures that the *contents* of brisk are copied, not brisk itself as a subdirectory
          cp -r ../flatpak-flutter/brisk/* .

          echo "Content of flathub-test after copying new files:"
          ls -la

          # --- Step 4: Commit and Push ---
          echo "Git status before add/commit:"
          git status
          echo "Git diff before add/commit:"
          git diff

          # Only proceed with commit if there are actual changes
          if ! git diff --quiet --exit-code; then
          echo "Changes detected, proceeding with commit."
          git add .
          git commit -m "Release ${{ needs.version.outputs.version }}"
          git push origin release-${{ needs.version.outputs.version }}
          else
          echo "No changes detected in flathub-test. Skipping commit and push."
          fi



      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPO_PAT }}
          commit-message: "Release ${{ needs.version.outputs.version }}"
          title: "Release ${{ needs.version.outputs.version }}"
          body: |
            This pull request was automatically generated by a GitHub Actions workflow.
          branch: release-${{ needs.version.outputs.version }}
          base: master
          path: flathub-test