name: Build and Upload Snap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: build

      - name: Upload to Snap Store
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_CREDENTIALS }}
        run: |
          snapcraft upload ./brisk_2.2.3_amd64.snap --release=stable
