name: Build Snap Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Install GTK 3 development packages
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: "3.29.3"
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' 
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' 
          architecture: x64

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Build Flutter Linux app
        run: flutter build linux

      - name: Build Snap inside Docker
        run: |
          docker run --rm \
            -v "$PWD:/workspace" \
            -w /workspace/linux \
            snapcore/snapcraft:stable \
            snapcraft

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-snap
          path: linux/*.snap
