name: Build snap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: build

      - name: Upload artifact 
        uses: actions/upload-artifact@v4.3.3
        with:
          name: brisk-package
          path: ./brisk_2.2.3_amd64.snap
          retention-days: 1
